"""OptimizationProposal — model for workflow optimization proposals.

Generated by the meta-workflow reflection engine or manually by users.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class ProposalStatus(StrEnum):
    """Lifecycle states for an optimization proposal."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"


class ProposalCreatedBy(StrEnum):
    """Origin of the proposal."""

    META_AGENT = "meta_agent"
    USER = "user"


class OptimizationProposal(BaseModel):
    """A proposed workflow optimization generated by the meta-agent.

    Maps to the ``optimization_proposals`` table created in migration v11.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    target_workflow_id: str
    source_session_id: str | None = None

    # Proposed changes (schema-compatible with WorkflowNode / WorkflowEdge)
    proposed_nodes: list[dict] = Field(default_factory=list)
    proposed_edges: list[dict] = Field(default_factory=list)

    rationale: str = ""
    risk_assessment: str = ""
    estimated_impact: str = ""

    status: ProposalStatus = ProposalStatus.PENDING
    created_by: ProposalCreatedBy = ProposalCreatedBy.META_AGENT
    approved_by: str | None = None
    approved_at: datetime | None = None

    # Version tracking
    parent_version_id: str = ""  # WorkflowDefinition.id being improved
    new_version_id: str | None = None  # Set after approval

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
